version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ali
    ports:
      - "5432:5432"
    volumes:
      - ali_pg:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ali_redis:/data
volumes:
  ali_pg:
  ali_redis:
